[package]
name = "minimal-api"
version = "0.1.0"
authors = ["Sumeet More"]
edition = "2018"

[dependencies]
actix-web = "3"
mobc = "0.7"
mobc-redis = { version = "0.7", default-features = false, features = ["async-std-comp"] }
redis = "0.19.0"
serde = "1"
serde_json = "1"